;;;; Constants

(in-package :cleric)

;;; Erlang data tags
(defconstant +compressed-term+    80)
(defconstant +new-float-ext+      70)
(defconstant +bit-binary-ext+     77)
(defconstant +atom-cache-ref+     82)
(defconstant +small-integer-ext+  97)
(defconstant +integer-ext+        98)
(defconstant +float-ext+          99)
(defconstant +atom-ext+          100)
(defconstant +reference-ext+     101)
(defconstant +port-ext+          102)
(defconstant +pid-ext+           103)
(defconstant +small-tuple-ext+   104)
(defconstant +large-tuple-ext+   105)
(defconstant +nil-ext+           106)
(defconstant +string-ext+        107)
(defconstant +list-ext+          108)
(defconstant +binary-ext+        109)
(defconstant +small-big-ext+     110)
(defconstant +large-big-ext+     111)
(defconstant +new-fun-ext+       112)
(defconstant +export-ext+        113)
(defconstant +new-reference-ext+ 114)
(defconstant +small-atom-ext+    115)
(defconstant +fun-ext+           117)
